"""empty message

Revision ID: 01b1e0095f5c
Revises: 1518830bbd75
Create Date: 2023-04-29 23:29:40.525865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b1e0095f5c'
down_revision = '1518830bbd75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
