"""empty message

Revision ID: 1518830bbd75
Revises: e1aed9231b5f
Create Date: 2023-04-29 23:24:40.786911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1518830bbd75'
down_revision = 'e1aed9231b5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
