"""empty message

Revision ID: 446ec2ac3685
Revises: 9c952289b070
Create Date: 2023-04-29 23:55:55.278347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446ec2ac3685'
down_revision = '9c952289b070'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
