"""empty message

Revision ID: b54a997547ae
Revises: 6a80357d008f
Create Date: 2023-04-30 00:45:00.564254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b54a997547ae'
down_revision = '6a80357d008f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_housebill_guidislink', table_name='housebill')
    op.drop_index('ix_housebill_hb_id', table_name='housebill')
    op.drop_index('ix_housebill_id', table_name='housebill')
    op.drop_index('ix_housebill_link', table_name='housebill')
    op.drop_index('ix_housebill_parss_cosponsors', table_name='housebill')
    op.drop_index('ix_housebill_parss_enacted', table_name='housebill')
    op.drop_index('ix_housebill_parss_lastaction', table_name='housebill')
    op.drop_index('ix_housebill_parss_passedhouse', table_name='housebill')
    op.drop_index('ix_housebill_parss_passedsenate', table_name='housebill')
    op.drop_index('ix_housebill_parss_primesponsor', table_name='housebill')
    op.drop_index('ix_housebill_published', table_name='housebill')
    op.drop_index('ix_housebill_published_parsed', table_name='housebill')
    op.drop_index('ix_housebill_summary', table_name='housebill')
    op.drop_index('ix_housebill_title', table_name='housebill')
    op.drop_table('housebill')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housebill',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hb_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('links', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_primesponsor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_cosponsors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_lastaction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_enacted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_passedhouse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_passedsenate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_parsed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('guidislink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='housebill_pkey')
    )
    op.create_index('ix_housebill_title', 'housebill', ['title'], unique=False)
    op.create_index('ix_housebill_summary', 'housebill', ['summary'], unique=False)
    op.create_index('ix_housebill_published_parsed', 'housebill', ['published_parsed'], unique=False)
    op.create_index('ix_housebill_published', 'housebill', ['published'], unique=False)
    op.create_index('ix_housebill_parss_primesponsor', 'housebill', ['parss_primesponsor'], unique=False)
    op.create_index('ix_housebill_parss_passedsenate', 'housebill', ['parss_passedsenate'], unique=False)
    op.create_index('ix_housebill_parss_passedhouse', 'housebill', ['parss_passedhouse'], unique=False)
    op.create_index('ix_housebill_parss_lastaction', 'housebill', ['parss_lastaction'], unique=False)
    op.create_index('ix_housebill_parss_enacted', 'housebill', ['parss_enacted'], unique=False)
    op.create_index('ix_housebill_parss_cosponsors', 'housebill', ['parss_cosponsors'], unique=False)
    op.create_index('ix_housebill_link', 'housebill', ['link'], unique=False)
    op.create_index('ix_housebill_id', 'housebill', ['id'], unique=False)
    op.create_index('ix_housebill_hb_id', 'housebill', ['hb_id'], unique=False)
    op.create_index('ix_housebill_guidislink', 'housebill', ['guidislink'], unique=False)
    # ### end Alembic commands ###
