"""empty message

Revision ID: e1aed9231b5f
Revises: 3a5a00a811d8
Create Date: 2023-04-29 22:52:38.031009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1aed9231b5f'
down_revision = '3a5a00a811d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datasets_guidislink', table_name='datasets')
    op.drop_index('ix_datasets_hb_id', table_name='datasets')
    op.drop_index('ix_datasets_id', table_name='datasets')
    op.drop_index('ix_datasets_link', table_name='datasets')
    op.drop_index('ix_datasets_links', table_name='datasets')
    op.drop_index('ix_datasets_parss_cosponsors', table_name='datasets')
    op.drop_index('ix_datasets_parss_enacted', table_name='datasets')
    op.drop_index('ix_datasets_parss_lastaction', table_name='datasets')
    op.drop_index('ix_datasets_parss_passedhouse', table_name='datasets')
    op.drop_index('ix_datasets_parss_passedsenate', table_name='datasets')
    op.drop_index('ix_datasets_parss_primesponsor', table_name='datasets')
    op.drop_index('ix_datasets_published', table_name='datasets')
    op.drop_index('ix_datasets_published_parsed', table_name='datasets')
    op.drop_index('ix_datasets_summary', table_name='datasets')
    op.drop_index('ix_datasets_summary_detail', table_name='datasets')
    op.drop_index('ix_datasets_title', table_name='datasets')
    op.drop_index('ix_datasets_title_detail', table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hb_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title_detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_primesponsor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_cosponsors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_lastaction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_enacted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_passedhouse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parss_passedsenate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_parsed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('guidislink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='datasets_pkey')
    )
    op.create_index('ix_datasets_title_detail', 'datasets', ['title_detail'], unique=False)
    op.create_index('ix_datasets_title', 'datasets', ['title'], unique=False)
    op.create_index('ix_datasets_summary_detail', 'datasets', ['summary_detail'], unique=False)
    op.create_index('ix_datasets_summary', 'datasets', ['summary'], unique=False)
    op.create_index('ix_datasets_published_parsed', 'datasets', ['published_parsed'], unique=False)
    op.create_index('ix_datasets_published', 'datasets', ['published'], unique=False)
    op.create_index('ix_datasets_parss_primesponsor', 'datasets', ['parss_primesponsor'], unique=False)
    op.create_index('ix_datasets_parss_passedsenate', 'datasets', ['parss_passedsenate'], unique=False)
    op.create_index('ix_datasets_parss_passedhouse', 'datasets', ['parss_passedhouse'], unique=False)
    op.create_index('ix_datasets_parss_lastaction', 'datasets', ['parss_lastaction'], unique=False)
    op.create_index('ix_datasets_parss_enacted', 'datasets', ['parss_enacted'], unique=False)
    op.create_index('ix_datasets_parss_cosponsors', 'datasets', ['parss_cosponsors'], unique=False)
    op.create_index('ix_datasets_links', 'datasets', ['links'], unique=False)
    op.create_index('ix_datasets_link', 'datasets', ['link'], unique=False)
    op.create_index('ix_datasets_id', 'datasets', ['id'], unique=False)
    op.create_index('ix_datasets_hb_id', 'datasets', ['hb_id'], unique=False)
    op.create_index('ix_datasets_guidislink', 'datasets', ['guidislink'], unique=False)
    # ### end Alembic commands ###
