
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."Bills" (
    "legislative_session" "text" NOT NULL,
    "chamber" "text" NOT NULL,
    "bill_number" bigint NOT NULL,
    "bill_internal_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "primary_sponsor_id" bigint,
    "status_text" "text",
    "session_type" "text" NOT NULL,
    "legislative_id" "text" NOT NULL,
    CONSTRAINT "Bills_legislative_id_check" CHECK (("legislative_id" ~ '^[0-9]{4}[0-1][HS][BR][0-9]+$'::"text")),
    CONSTRAINT "Bills_session_type_check" CHECK (("session_type" = ANY (ARRAY['0'::"text", '1'::"text"])))
);

ALTER TABLE "public"."Bills" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."Bills_Old" (
    "id" bigint NOT NULL,
    "title" "text",
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "session_no" "text",
    "primary_sponsor_id" bigint,
    "active_revision_id" bigint,
    "bill_id" bigint,
    "status_text" "text",
    "chamber" "text"
);

ALTER TABLE "public"."Bills_Old" OWNER TO "postgres";

ALTER TABLE "public"."Bills" ALTER COLUMN "bill_internal_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Bills_bill_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Bills_Old" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."HouseBill_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Policy_Test" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text"
);

ALTER TABLE "public"."Policy_Test" OWNER TO "postgres";

ALTER TABLE "public"."Policy_Test" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Policy_Test_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Representatives" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "first_name" "text",
    "last_name" "text",
    "party" "text",
    "distrinct" bigint,
    "profile_link" "text",
    "chamber" "text"
);

ALTER TABLE "public"."Representatives" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."Summaries" (
    "summary_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "revision_internal_id" bigint,
    "summary_text" "text"
);

ALTER TABLE "public"."Summaries" OWNER TO "postgres";

ALTER TABLE "public"."Summaries" ALTER COLUMN "summary_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RevisionSummaries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Revision_Text" (
    "rt_unique_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "full_text" "text"
);

ALTER TABLE "public"."Revision_Text" OWNER TO "postgres";

ALTER TABLE "public"."Revision_Text" ALTER COLUMN "rt_unique_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Revision_Text_rt_unique_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Revisions" (
    "revision_guid" "text" NOT NULL,
    "revision_internal_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "printer_no" bigint,
    "full_text_link" "text",
    "publication_date" "date",
    "rt_unique_id" bigint,
    "active_summary_id" bigint,
    "description" "text",
    "bill_internal_id" bigint,
    "bill_id" bigint,
    CONSTRAINT "Revisions_New_revision_guid_check" CHECK (("revision_guid" ~ '^[0-9]{4}[0-1][HS][BR][0-9]+P[0-9]+$'::"text"))
);

ALTER TABLE "public"."Revisions" OWNER TO "postgres";

ALTER TABLE "public"."Revisions" ALTER COLUMN "revision_internal_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Revisions_New_revision_internal_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Revisions_Old" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "bill_id_old" bigint,
    "printer_no" bigint,
    "full_text_link" "text",
    "publication_date" "date",
    "full_text" "text",
    "active_summary_id" bigint,
    "legislative_body" "text",
    "bill_id" bigint
);

ALTER TABLE "public"."Revisions_Old" OWNER TO "postgres";

ALTER TABLE "public"."Revisions_Old" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Revisions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Representatives" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Sponsor_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."bill_revisions" (
    "bill_internal_id" bigint NOT NULL,
    "revision_id" integer NOT NULL
);

ALTER TABLE "public"."bill_revisions" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."bill_sponsors" (
    "bill_id" bigint NOT NULL,
    "sponsor_id" integer NOT NULL
);

ALTER TABLE "public"."bill_sponsors" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."bill_tags" (
    "bill_internal_id" bigint NOT NULL,
    "tag_id" integer NOT NULL
);

ALTER TABLE "public"."bill_tags" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."revisions" (
    "internal_id" integer NOT NULL,
    "printer_no" character varying,
    "external_link" character varying,
    "publication_date" "date",
    "full_text" character varying,
    "gpt_summary" character varying,
    "internal_created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "internal_updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);

ALTER TABLE "public"."revisions" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."revisions_internal_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."revisions_internal_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."revisions_internal_id_seq" OWNED BY "public"."revisions"."internal_id";

CREATE TABLE IF NOT EXISTS "public"."sponsor_table" (
    "internal_id" integer NOT NULL,
    "first_name" character varying,
    "last_name" character varying,
    "party" character varying,
    "profile_link" character varying,
    "internal_created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "internal_updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    CONSTRAINT "sponsor_table_party_check" CHECK ((("party")::"text" = ANY (ARRAY[('democrat'::character varying)::"text", ('republican'::character varying)::"text"])))
);

ALTER TABLE "public"."sponsor_table" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."sponsor_table_internal_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."sponsor_table_internal_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."sponsor_table_internal_id_seq" OWNED BY "public"."sponsor_table"."internal_id";

CREATE TABLE IF NOT EXISTS "public"."tags" (
    "internal_id" integer NOT NULL,
    "text" character varying,
    "slug" character varying
);

ALTER TABLE "public"."tags" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."tags_internal_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."tags_internal_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."tags_internal_id_seq" OWNED BY "public"."tags"."internal_id";

ALTER TABLE ONLY "public"."revisions" ALTER COLUMN "internal_id" SET DEFAULT "nextval"('"public"."revisions_internal_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."sponsor_table" ALTER COLUMN "internal_id" SET DEFAULT "nextval"('"public"."sponsor_table_internal_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."tags" ALTER COLUMN "internal_id" SET DEFAULT "nextval"('"public"."tags_internal_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."Bills"
    ADD CONSTRAINT "Bills_bill_id_key" UNIQUE ("bill_internal_id");

ALTER TABLE ONLY "public"."Bills"
    ADD CONSTRAINT "Bills_legislative_id_key" UNIQUE ("legislative_id");

ALTER TABLE ONLY "public"."Bills"
    ADD CONSTRAINT "Bills_pkey" PRIMARY KEY ("legislative_id");

ALTER TABLE ONLY "public"."Bills_Old"
    ADD CONSTRAINT "HouseBill_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Policy_Test"
    ADD CONSTRAINT "Policy_Test_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Summaries"
    ADD CONSTRAINT "RevisionSummaries_pkey" PRIMARY KEY ("summary_id");

ALTER TABLE ONLY "public"."Revision_Text"
    ADD CONSTRAINT "Revision_Text_pkey" PRIMARY KEY ("rt_unique_id");

ALTER TABLE ONLY "public"."Revision_Text"
    ADD CONSTRAINT "Revision_Text_rt_unique_id_key" UNIQUE ("rt_unique_id");

ALTER TABLE ONLY "public"."Revisions"
    ADD CONSTRAINT "Revisions_New_pkey" PRIMARY KEY ("revision_guid");

ALTER TABLE ONLY "public"."Revisions"
    ADD CONSTRAINT "Revisions_New_revision_internal_id_key" UNIQUE ("revision_internal_id");

ALTER TABLE ONLY "public"."Revisions_Old"
    ADD CONSTRAINT "Revisions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Representatives"
    ADD CONSTRAINT "Sponsor_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."bill_revisions"
    ADD CONSTRAINT "bill_revisions_pkey" PRIMARY KEY ("bill_internal_id", "revision_id");

ALTER TABLE ONLY "public"."bill_sponsors"
    ADD CONSTRAINT "bill_sponsors_pkey" PRIMARY KEY ("bill_id", "sponsor_id");

ALTER TABLE ONLY "public"."bill_tags"
    ADD CONSTRAINT "bill_tags_pkey" PRIMARY KEY ("bill_internal_id", "tag_id");

ALTER TABLE ONLY "public"."revisions"
    ADD CONSTRAINT "revisions_pkey" PRIMARY KEY ("internal_id");

ALTER TABLE ONLY "public"."sponsor_table"
    ADD CONSTRAINT "sponsor_table_pkey" PRIMARY KEY ("internal_id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("internal_id");

ALTER TABLE ONLY "public"."Bills_Old"
    ADD CONSTRAINT "Bills_Old_active_revision_id_fkey" FOREIGN KEY ("active_revision_id") REFERENCES "public"."Revisions_Old"("id");

ALTER TABLE ONLY "public"."Bills_Old"
    ADD CONSTRAINT "Bills_Old_primary_sponsor_id_fkey" FOREIGN KEY ("primary_sponsor_id") REFERENCES "public"."Representatives"("id");

ALTER TABLE ONLY "public"."Revisions_Old"
    ADD CONSTRAINT "Revisions_Old_active_summary_id_fkey" FOREIGN KEY ("active_summary_id") REFERENCES "public"."Summaries"("summary_id");

ALTER TABLE ONLY "public"."Revisions_Old"
    ADD CONSTRAINT "Revisions_Old_bill_id_old_fkey" FOREIGN KEY ("bill_id_old") REFERENCES "public"."Bills_Old"("id");

ALTER TABLE ONLY "public"."Revisions"
    ADD CONSTRAINT "Revisions_active_summary_id_fkey" FOREIGN KEY ("active_summary_id") REFERENCES "public"."Summaries"("summary_id");

ALTER TABLE ONLY "public"."Revisions"
    ADD CONSTRAINT "Revisions_bill_internal_id_fkey" FOREIGN KEY ("bill_internal_id") REFERENCES "public"."Bills"("bill_internal_id");

ALTER TABLE ONLY "public"."Revisions"
    ADD CONSTRAINT "Revisions_rt_unique_id_fkey" FOREIGN KEY ("rt_unique_id") REFERENCES "public"."Revision_Text"("rt_unique_id");

ALTER TABLE ONLY "public"."Summaries"
    ADD CONSTRAINT "Summaries_revision_internal_id_fkey" FOREIGN KEY ("revision_internal_id") REFERENCES "public"."Revisions"("revision_internal_id");

ALTER TABLE ONLY "public"."bill_revisions"
    ADD CONSTRAINT "bill_revisions_bill_internal_id_fkey" FOREIGN KEY ("bill_internal_id") REFERENCES "public"."Bills"("bill_internal_id");

ALTER TABLE ONLY "public"."bill_revisions"
    ADD CONSTRAINT "bill_revisions_revision_id_fkey" FOREIGN KEY ("revision_id") REFERENCES "public"."revisions"("internal_id");

ALTER TABLE ONLY "public"."bill_sponsors"
    ADD CONSTRAINT "bill_sponsors_bill_id_fkey" FOREIGN KEY ("bill_id") REFERENCES "public"."Bills"("bill_internal_id");

ALTER TABLE ONLY "public"."bill_sponsors"
    ADD CONSTRAINT "bill_sponsors_sponsor_id_fkey" FOREIGN KEY ("sponsor_id") REFERENCES "public"."sponsor_table"("internal_id");

ALTER TABLE ONLY "public"."bill_tags"
    ADD CONSTRAINT "bill_tags_bill_internal_id_fkey" FOREIGN KEY ("bill_internal_id") REFERENCES "public"."Bills"("bill_internal_id");

ALTER TABLE ONLY "public"."bill_tags"
    ADD CONSTRAINT "bill_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("internal_id");

ALTER TABLE "public"."Bills" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Bills_Old" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for authenticated users only" ON "public"."Policy_Test" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."Bills_Old" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Representatives" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Revisions_Old" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Summaries" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."bill_revisions" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."bill_sponsors" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."bill_tags" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."revisions" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sponsor_table" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."tags" FOR SELECT USING (true);

ALTER TABLE "public"."Policy_Test" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Representatives" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Revision_Text" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Revisions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Revisions_Old" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Summaries" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."bill_revisions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."bill_sponsors" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."bill_tags" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."revisions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sponsor_table" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."Bills" TO "anon";
GRANT ALL ON TABLE "public"."Bills" TO "authenticated";
GRANT ALL ON TABLE "public"."Bills" TO "service_role";

GRANT ALL ON TABLE "public"."Bills_Old" TO "anon";
GRANT ALL ON TABLE "public"."Bills_Old" TO "authenticated";
GRANT ALL ON TABLE "public"."Bills_Old" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Bills_bill_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Bills_bill_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Bills_bill_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."HouseBill_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."HouseBill_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."HouseBill_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Policy_Test" TO "anon";
GRANT ALL ON TABLE "public"."Policy_Test" TO "authenticated";
GRANT ALL ON TABLE "public"."Policy_Test" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Policy_Test_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Policy_Test_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Policy_Test_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Representatives" TO "anon";
GRANT ALL ON TABLE "public"."Representatives" TO "authenticated";
GRANT ALL ON TABLE "public"."Representatives" TO "service_role";

GRANT ALL ON TABLE "public"."Summaries" TO "anon";
GRANT ALL ON TABLE "public"."Summaries" TO "authenticated";
GRANT ALL ON TABLE "public"."Summaries" TO "service_role";

GRANT ALL ON SEQUENCE "public"."RevisionSummaries_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RevisionSummaries_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RevisionSummaries_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Revision_Text" TO "anon";
GRANT ALL ON TABLE "public"."Revision_Text" TO "authenticated";
GRANT ALL ON TABLE "public"."Revision_Text" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Revision_Text_rt_unique_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Revision_Text_rt_unique_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Revision_Text_rt_unique_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Revisions" TO "anon";
GRANT ALL ON TABLE "public"."Revisions" TO "authenticated";
GRANT ALL ON TABLE "public"."Revisions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Revisions_New_revision_internal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Revisions_New_revision_internal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Revisions_New_revision_internal_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Revisions_Old" TO "anon";
GRANT ALL ON TABLE "public"."Revisions_Old" TO "authenticated";
GRANT ALL ON TABLE "public"."Revisions_Old" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Revisions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Revisions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Revisions_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Sponsor_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Sponsor_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Sponsor_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."bill_revisions" TO "anon";
GRANT ALL ON TABLE "public"."bill_revisions" TO "authenticated";
GRANT ALL ON TABLE "public"."bill_revisions" TO "service_role";

GRANT ALL ON TABLE "public"."bill_sponsors" TO "anon";
GRANT ALL ON TABLE "public"."bill_sponsors" TO "authenticated";
GRANT ALL ON TABLE "public"."bill_sponsors" TO "service_role";

GRANT ALL ON TABLE "public"."bill_tags" TO "anon";
GRANT ALL ON TABLE "public"."bill_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."bill_tags" TO "service_role";

GRANT ALL ON TABLE "public"."revisions" TO "anon";
GRANT ALL ON TABLE "public"."revisions" TO "authenticated";
GRANT ALL ON TABLE "public"."revisions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."revisions_internal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."revisions_internal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."revisions_internal_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sponsor_table" TO "anon";
GRANT ALL ON TABLE "public"."sponsor_table" TO "authenticated";
GRANT ALL ON TABLE "public"."sponsor_table" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sponsor_table_internal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sponsor_table_internal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sponsor_table_internal_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tags_internal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_internal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_internal_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
