name: ETL_TEST

on: 
  workflow_dispatch:

env: 
  SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

jobs:
  etl-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v3
      - name: Setup Python 
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
      - name: Install Python Packages
        run: |
          pip install pipenv
          pipenv install --deploy --dev
      - name: Run Main RSS and DOCX Text extraction file
        run: src/web_scraper/web_scraper.py #maybe split main functions into separate files  
        #needs: #add dependency to setup  